# Generated by Django 2.0.7 on 2018-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slpu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur', models.FloatField(blank=True, null=True)),
                ('vozr', models.FloatField(blank=True, null=True)),
                ('name_issl', models.CharField(blank=True, max_length=255, null=True)),
                ('ksg', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('type', models.FloatField(blank=True, null=True)),
                ('sr_preb', models.FloatField(blank=True, null=True)),
                ('idpr', models.FloatField(blank=True, null=True)),
                ('kdprice', models.FloatField(blank=True, null=True)),
                ('idump', models.FloatField(blank=True, null=True)),
                ('nozol', models.CharField(blank=True, max_length=255, null=True)),
                ('kol_usl', models.FloatField(blank=True, null=True)),
                ('t_type', models.FloatField(blank=True, null=True)),
                ('intp', models.FloatField(blank=True, null=True)),
                ('idvmp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sp_tarif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XmlPacientExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pac', models.CharField(max_length=36)),
                ('vpolis', models.BigIntegerField(blank=True, null=True)),
                ('spolis', models.CharField(blank=True, max_length=10, null=True)),
                ('npolis', models.CharField(blank=True, max_length=20, null=True)),
                ('st_okato', models.CharField(blank=True, max_length=15, null=True)),
                ('smo', models.CharField(blank=True, max_length=5, null=True)),
                ('smo_ogrn', models.CharField(blank=True, max_length=15, null=True)),
                ('smo_ok', models.CharField(blank=True, max_length=5, null=True)),
                ('smo_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('novor', models.CharField(blank=True, max_length=8, null=True)),
                ('vnov_d', models.CharField(blank=True, max_length=10, null=True)),
                ('glpu', models.CharField(max_length=6)),
                ('period', models.DateField()),
            ],
            options={
                'db_table': 'xml_pacient_ext',
                'managed': False,
            },
        ),
    ]
