# Generated by Django 2.0.7 on 2018-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hkod', models.CharField(max_length=24)),
                ('name_o', models.CharField(max_length=120)),
                ('price', models.FloatField(blank=True, null=True)),
                ('notksg', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'oper',
                'managed': False,
            },
        ),
    ]
