# Generated by Django 2.0.7 on 2018-09-16 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_filedbf'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedbf',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 16, 29, 54, 446314), verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='filedbf',
            name='file',
            field=models.FileField(upload_to='files/dbf/', verbose_name='Путь к файлу'),
        ),
    ]
