# Generated by Django 2.0.7 on 2018-09-16 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20180916_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oper',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterField(
            model_name='filedbf',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 17, 20, 38, 937038), verbose_name='Дата загрузки'),
        ),
    ]
