# Generated by Django 2.0.7 on 2018-09-16 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20180916_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oper',
            name='id',
        ),
        migrations.AlterField(
            model_name='filedbf',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 17, 28, 4, 220879), verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='oper',
            name='hkod',
            field=models.CharField(blank=True, max_length=50, null=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oper',
            name='name_o',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='oper',
            name='notksg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
