# Generated by Django 2.0.7 on 2018-09-16 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20180916_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedbf',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='filedbf',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 19, 5, 4, 845436), verbose_name='Дата загрузки'),
        ),
        migrations.AlterModelTable(
            name='oper',
            table=None,
        ),
    ]
